{{- if (and .Values.installCRDs (not (.Capabilities.APIVersions.Has "mysql.radondb.io/v1"))) }}
{{- if and .Values.installCRDs -}}
{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
---
{{ $.Files.Get $path }}
{{- end }}
{{- end }}
{{- end }}
